development:
  sessions:
    default:
      database: rcran_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: rcran_test
      hosts:
        - localhost:27017
